# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ic4KTgIA556bolmylvAUknLupW_x4a9K
"""

base=int(input("ingrese la base: "))
altura=int(input("ingrese la altura: "))

area=base*altura/2
print("el area del triangulo es: ",area)