# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s5S15_-PynIc551tGc4Vz6U_RUjNBhKF
"""

metros=int(input("ingrece la cantidad de metros es: "))
precio=int(input("ingrese la cantidad por metro es: "))

total=precio*metros
print(f"la catidad es: ", total)