# -*- coding: utf-8 -*-
"""calcular tiempo de viaje

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UijorURR5HlpqsCcRzTpAyMI-kxyUAj5
"""

#definir variable
tiempo:float
distancia:float
velocidad:float
#datos de entrada
distancia=float(input("ingrese la distancia:"))
velocidad=float(input("ingrese a cuanta velocidad va:"))
#proceso
tiempo=(distancia/velocidad)
#datos de salida
print(f"el tiempo de manejo es: ", tiempo)