# -*- coding: utf-8 -*-
"""calcular cobro de estacionamiento

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1waRnaZRwkZY821WOXgrWRSasCAwZm-m2
"""

#definir variable
horas:float
promocion:float
pago:float
#datos de entrada
pago=float(input("dame el mumero de horas consumida: "))
#proceso
promocion = (pago / 10)
total = pago - promocion
#datos de salida 
print(f"usted debe pagar ", total, "soles")