# -*- coding: utf-8 -*-
"""cantidad de consumo de agua por metros cúbicos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KWNKikR8rGwAUZkQ3JRbYO-PBZOG2Fiu
"""

#definir variable
costo:float
pago:float
MCU:float
#datos de entrada
MCU=float(input("ingrese la cantidad de metros cubicos usados:"))
costo=float(input("ingrese el costo en soles por metro cubico"))
#proceso
pago=(MCU*costo)
#datos de salida
print(f"total a pagar en soles es: ", pago)