# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bAp4NT74Am9MDOwrTkfy-O40_DVwQ3ob
"""

#definir variable
soles:float
dolares:float
#datos de entrada
soles=float(input("ingrese cantidad:"))
#proceso
dolares=soles/3.84
#pocesos de salida 
print(f"la catidad es: {dolares}")