# -*- coding: utf-8 -*-
"""tiempo de llamada

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yRP0Zjjg6JmA7YCotaDpw8ply11enAOW
"""

minutos=float(input("ingrese la cantidad de minutos: "))
precio=float(input("ingrese el precio por minuto: "))

total=minutos*precio
print(f"la cantidad a pagar es: ", total)