# -*- coding: utf-8 -*-
"""Ejercicio 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1slraaXF3zC3M21PoUNLq_QVyV5GfkmEo
"""

#definir variables
costo:float
horas:float=1.00
mensaje:str
#datos de entrada
horas=int(input("dame las horas quedadas en el estacionamiento: "))
costo=float(input("dame el costo por hora:"))
#proceso
if horas<=2:
   mensaje=(f"debe pagar 5.00")
if horas>=3 and horas<=4:
   mensaje=(f"debe pagar 4.00")
if horas>=5 and horas<=9:
   mensaje=(f"debe pagar 3.00")
if horas>=10:
   mensaje=(f"debe pagar 2.00")
costofinal=horas*costo
#datos de salida
print(f"el costo final es: {costofinal}")

"""Plaza Vea requiere un algoritmo que le permita determinar cuánto debe cobrar por el uso su estacionamiento a sus clientes. Las tarifas que se tienen son las siguientes:
Las dos primeras horas es a S/ 5.00 c/h
Las siguientes tres horas es a S/ 4.00 c/h
Los cinco siguientes a S/ 3.00 c/h
Después de diez horas el costo por cada una es de S/2.00 



"""