# -*- coding: utf-8 -*-
"""Ejercicio 6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17g6jsUfrkSGycE1hJ3yFHMXRWRiCsDF9
"""

#definir variables
costo:int
descuento:float
mensaje:str
#datos de entrada
costo=int(input("ingrese el costo: "))
descuento=float(input("ingrese el descuento %:"))
#proceso
if costo >=200:
   mensaje= "puede tener descuento de: 15%"
if costo >=100 and costo <=200:
   mensaje= "puede tener un descuento de: 12%"
if costo <=100: 
   mensaje= "puede tener un descuento de: 10%"
preciototal=costo*descuento
#datos de salida
print(f"costo total es:{mensaje}")

#proceso
preciototal=costo*descuento
#satos de salida
print(f"precio total es: {preciototal}")

"""Realice un algoritmo para determinar el costo y el descuento que tendrá un artículo. Considere que, si su precio es mayor o igual a S/ 200 se le aplica un descuento de 15%, y si su precio es mayor a S/ 100 pero menor a S/ 200 el descuento es de 12% y si es menor a 100 solo es de 10%."""