# -*- coding: utf-8 -*-
"""calcular edad

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ob1ZvmM-mtkd8enVyX0WqzN_DjXOP0o
"""

#definir valiable
año_actual:float=2022
mes_actual:float=4
dia_actual:float=30
#datos de entrada
año_nacimiento = int(input("ingrese su año de nacimiento: "));
mes_nacimiento = int(input("ingrese su mes de nacimiento: "));
dia_nacimiento = int(input("ingrese su dia de nacimiento: "));
#proceso

edad=año_actual - año_nacimiento

#datos de salida
print(f"la edad es: ",edad)

