# -*- coding: utf-8 -*-
"""Ejercicio 10

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1w693xlazSpWICY4wzVOAWiPsBRuAudW4
"""

#definir variables
cobrokilometro:float
costokilometro:float
costopasaje:float
mensaje:str
kilometro:int
#datos de entrada
kilometro=float(input("agregue los kilometros recorrifos: "))

#proceso
if kilometro >= 1800:
   mensaje="tumbes"

if kilometro <= 800 and kilometro >=751:
   mensaje="chiclayo"

if kilometro <= 750 and kilometro>=1:
   mensaje="tacna"

if kilometro<=0:
   mensaje="quedarse en casa"
#datos de salida
print(f"puede viajar a: {mensaje}")