# -*- coding: utf-8 -*-
"""Ejercicio 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19yBBbrmWvIRZ7Tpj7ujZPLO1vcvdJYS2
"""

#definir variables
costo:int
flores:int
chocolates:int
tarjetas:int
mensaje:str
#datos de entrada
costo=int(input("ingrese el costo:"))
#proceso
if costo>=251:
   mensaje=(f"puede comprar el anillo")
if costo>=101 and costo<=250:
   mensaje=str(f"puede comprar flores")
elif costo<=10:
    mensaje=str(f"puede comprar una tarjeta")
elif costo>=11 and costo<=100:
    mensaje=str(f"puede compar chocolates")       
#datos de salida
print(f"puede comprar: {mensaje}  ")

"""El 14 de febrero una persona desea comprarle un regalo al ser querido que más aprecia en ese momento, su dilema radica En qué regalo puede hacerle, las alternativas que tiene son las siguientes: 

Regalo	Costo
Tarjeta	S/. 10.00 o menos
Chocolate	S/. 11.00 a S/. 100.00
Flores	S/. 101.00 a S/. 250.00
Anillo	Más de S/. 251.00

Realice el algoritmo que ayude a determinar qué regalo se le puede comprar a ese ser tan especial por el día del amor y la amistad.

Realice un algoritmo para determinar el sueldo semanal de un trabajador con base a las horas trabajadas y el pago por hora, considerando que después de las 40 horas cada hora se considera como excedente y se paga el doble.
"""