# -*- coding: utf-8 -*-
"""Untitled0.ipynb  costo de pasaje por km

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KO9UX3d_FNsY-nylTXRVORcxSitdTKCW
"""

precio=float(input("ingrese el precio por kilometro: "))
kilometro=float(input("imgrese la cantidad de kilometro: "))

total=(precio*kilometro)
print(f"la catidad a pagar es: ",total)