# -*- coding: utf-8 -*-
"""hipotenusa triangulo

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/180Q9SweqF17SU4mDJUeWSi8S3juCxf5R
"""

#definir variables
cateto_opuesto:float
cateto_adyacente:float
hipotenusa:float
#datos de entrada
cateto_opuesto=float(input("ingrese el cateto opuesto: "))
cateto_adyacente=float(input("ingrese el cateto adyacente: "))
#proceso
hipotenusa = (cateto_opuesto**2 + cateto_adyacente**2)
#datos de salida
print("la hipotenusa es: ", hipotenusa)