# -*- coding: utf-8 -*-
"""Ejercicio 2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RhcEgv8MEE7zEjLPAuDg8C9vG_WB_vBE
"""

#Declarar Variables
pagohora:int
cantidadhora:int
sueldototal:str
horaextra:int
#Datos de Entrada
pagohora = int ( input ( "Ingrese el costo por hora:  " ))
cantidadhora = int ( input ( "Ingrese cantidad de horas trabajadas en la semana: " ))
horasextr = int ( input ( "Ingrese cantidad de horas extras trabajadas en la semana: " ))
#Proceso 
sueldototal=pagohora*cantidadhora
horaextra=pagohora*8
#Datos de Salida
print(f"El sueldo del trabajador es: { sueldototal } " )

#proceso

sueldomensual = horaextra+sueldototal
#datos de salida
print(f"El sueldo  mensual del trabajador es: { sueldomensual} " )

"""Realice un algoritmo para determinar el sueldo semanal de un trabajador con base a las horas trabajadas y el pago por hora, considerando que después de las 40 horas cada hora se considera como excedente y se paga el doble."""