# -*- coding: utf-8 -*-
"""Ejercicio 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Loyy1vA-PlInIwZA9TFaMBR2sJlesrWF
"""

#Declarar Variables
nombre1 : str
nombre2 : str
nombre3 : str
edad1 : int
edad2 : int
edad3 : int
menorpersona : str
menoredad : int
#Datos de entrada
nombre1 = str ( input ( "Ingrese nombre 1:" ))
edad1 = str ( input ( "Ingrese edad de persona 1:" ))
nombre2 = str ( input ( "Ingrese nombre 2:" ))
edad2 = str ( input ( "Ingrese edad de persona 2:" ))
nombre3 = str ( input ( "Ingrese nombre 3:" ))
edad3 = str ( input ( "Ingrese edad de persona 3:" ))
#Proceso
if  edad1 <= edad2 and edad1 <= edad3 :
  menoredad = edad1
  menorpersona = nombre1
if  edad2 <= edad1  and  edad2 <= edad3 :
  menoredad = edad2
  menorpersona = nombre2
if edad3<= edad1 and edad3<= edad2:
  menoredad = edad3
  menorpersona = nombre3
#Datos de Salida
print(f"La persona con menor edad es: { menoredad } y se llama { menorpersona } ")

"""Se tiene el nombre y la edad de 3 personas. Se desea saber el nombre y la edad de la persona de menor edad. Realice el algoritmo correspondiente."""