# -*- coding: utf-8 -*-
"""Ejercicio 11

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kPLzE7wTxgvbVuinDbHU9VZ8hxMRzPCN
"""

#definir variable
antiguedad:float
bono:float
#datos de entrada
antiguedad=float(input("ingrese antiguedad"))
#proceso y datos de salida
if antiguedad==1:
   bono=100
elif antiguedad==2:
   bono=200
elif antiguedad==3:
   bono=300
elif antiguedad==4:
   bono=400
else:
   antiguedad<=5
   bono=500
   bono=1000
#datos de salida
print(f"tu bono correspondiente es{bono}")

"""Se les dará un Bono por antigüedad a los empleados de una tienda.  Si tienen un año, se le dará S/ 100, si tiene 2 años, S/ 200, y así sucesivamente hasta los 5 años. Para los que tengan más de 5, será de S/ 1000. Realice un algoritmo que permita determinar el bono que recibirá un trabajador."""