# -*- coding: utf-8 -*-
"""Ejercicio 7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q3XNlQBUSLPdtGNheEkrFXHRxZ0rbwSZ
"""

#definir variables
edad:int
promedio:int
becas:str
mensaje:str
#datos de entrada
edad=float(input("ingrese la edad: "))
promedio=float(input("ingrese su promedio: "))
#proceso
if edad>18:
   promedio>=18
   mensaje="2000"
if promedio<=17 and promedio>=15:
   mensaje="1000"
if promedio<=12 and promedio>=15:
   mensaje="500"   
#datos de salida
print(f"su beca seria: {mensaje}")

#definir variables
edad:int
promedio:int
alumnos:str
becas:str
mensaje:str
#datos de entrada
edad=int(input("ingrese la edad: "))
promedio=float(input("ingrese su promedio: "))
#proceso  
if edad<18 :
   promedio>18
   mensaje="3000"
if promedio<18 and promedio>=16:
   mensaje="2000"
if promedio<16 and promedio>=12:
   mensaje="100"
if promedio<12:
   mensaje="se enviara una carta de invitacion"
#datos de salida
print(f"su beca seria: {mensaje}")

""" El presidente de la República ha decidido estimular a todos los estudiantes de la universidad mediante la asignación de becas mensuales para esto se tomará en consideración los siguientes criterios.
Para alumnos mayores de 18 años con promedio mayor o igual a 18 la beca será de S/ 2000; con promedio mayor o igual a 15 de S/ 1000; para los promedios menores de 15 pero mayores o iguales a 12. de S/ 500; a los demás se les enviará una carta de invitación invitándolos a que estudien más en el próximo ciclo académico. A los alumnos de 18 años o menores de esta edad con promedios mayores o iguales a 18 se les dará S/ 3000; con promedios menores a 18 pero mayores o iguales a 16, S/ 2000; para los alumnos con promedios menores a 16 pero mayores o iguales a 12 se les dará S/ 100, y a los alumnos que tengan promedio menor a 12 se les enviará una carta de invitación. Realice el algoritmo correspondiente. 

"""