# -*- coding: utf-8 -*-
"""Ejercicio 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pedsiojGlu9bINtGxBkPR68y3s0zn92n
"""

#definir variables
añonacimiento:float=2003
añoactual:float=2022
#datos de entrada 
añonacimiento=int(input("ingrese el año de nacimiento: "));
añoactual=int(input("ingrese el año actual: "));
#proceso
edad=añoactual-añonacimiento
#datos de salida
print((f"puedes votar:", edad>=18), (f"no puedes votar:", edad<=18))